name: "ADB Server"
version: "1.0.0"
slug: "adb_server"
description: "ADB Server Add-on voor Home Assistant"
arch:
  - amd64
  - armhf
  - aarch64
startup: "services"
boot: "auto"
ports:
  5037/tcp: 5037
options: {}
schema: {}
